sap.ui.define(
	["sap/ui/model/json/JSONModel", "sap/ui/model/BindingMode", "sap/ui/Device"],
	function (JSONModel, BindingMode, Device) {
		"use strict";

		return {
			createDeviceModel: function () {
				const oModel = new JSONModel(Device);
				oModel.setDefaultBindingMode(BindingMode.OneWay);
				return oModel;
			},
			createMainModel: function () {
				return new JSONModel({
					visibility: false,
					editable: false,
					enabled: false,
					busy: false,
					selected: false,
					isDetail: false,
				});
			},
			createSizesModel: function () {
				return new JSONModel({
					masterPaneSize: "320px",
					detailPaneSize: "auto",
					menuExpanded: true,
				});
			},
			createMockData: function () {
				return new JSONModel({
					activityTypes: [
						{
							LSTAR: "ACT001",
							KTEXT: "Plant Maintenance",
							DATBI: "20251231",
							DATAB: "20240101",
							OPERA: "INS",
							positions: [
								{
									KOSTL: "CC1001",
									YEAR: "2025",
									MONTH: "01",
									PLAN: "X",
								},
								{
									KOSTL: "CC1002",
									YEAR: "2025",
									MONTH: "02",
									PLAN: "",
								},
							],
						},
						{
							LSTAR: "ACT002",
							KTEXT: "Production Line A",
							DATBI: "20251231",
							DATAB: "20240101",
							OPERA: "INS",
							positions: [
								{
									KOSTL: "CC1001",
									YEAR: "2025",
									MONTH: "03",
									PLAN: "X",
								},
							],
						},
						{
							LSTAR: "ACT003",
							KTEXT: "Quality Control",
							DATBI: "20251231",
							DATAB: "20230101",
							OPERA: "MOD",
							positions: [
								{
									KOSTL: "CC1002",
									YEAR: "2024",
									MONTH: "12",
									PLAN: "",
								},
							],
						},
						{
							LSTAR: "ACT004",
							KTEXT: "Operator Training",
							DATBI: "20221231",
							DATAB: "20210101",
							OPERA: "DEL",
							positions: [
								{
									KOSTL: "CC1003",
									YEAR: "2022",
									MONTH: "06",
									PLAN: "X",
								},
							],
						},
					],
					costCentersADP: [
						{
							code: "CCADP1001",
							name: "IT Department",
							DATBI: "20251231",
							DATAB: "20240101",
							inactiveIndicator: false,
						},
						{
							code: "CCADP1002",
							name: "HR Department",
							DATBI: "20251231",
							DATAB: "20240101",
							inactiveIndicator: true,
						},
						{
							code: "CCADP1003",
							name: "Finance Department",
							DATBI: "20241231",
							DATAB: "20220101",
							inactiveIndicator: false,
						},
					],
					employeesS4: [
						{
							USRID: "jsmith",
							HIRE_DATE: "20220110",
							BUKRS: "1000",
							WERKS: "2000",
							KOSTL: "CC1001",
							PERSG: "A1",
							PERSK: "A1-FT",
							BTRTL: "HQ01",
							ANRED: "Mr.",
							VORNA: "John",
							NACHN: "Smith",
							GBDAT: "19850412",
							GBORT: "London",
							NATIO: "UK",
							GESCH: "M",
							SPRSL: "EN",
							EMAIL: "john.smith@company.com",
							ADP_ID: "ADP12345",
							PERSON_ID_EXT: "SF1001",
							LSTAR: "ACT001",
							ICNUM: "AB123456C",
						},
						{
							USRID: "amiller",
							HIRE_DATE: "20210305",
							BUKRS: "2000",
							WERKS: "3000",
							KOSTL: "CC2001",
							PERSG: "B2",
							PERSK: "B2-PT",
							BTRTL: "PLT02",
							ANRED: "Ms.",
							VORNA: "Anna",
							NACHN: "Miller",
							GBDAT: "19900225",
							GBORT: "Berlin",
							NATIO: "DE",
							GESCH: "F",
							SPRSL: "DE",
							EMAIL: "anna.miller@company.com",
							ADP_ID: "ADP67890",
							PERSON_ID_EXT: "SF2001",
							LSTAR: "ACT002",
							ICNUM: "CD987654D",
						},
					],
					employeesTS: [
						{
							personIdExternal: "E1001",
							firstName: "John",
							lastName: "Doe",
							title: "Software Engineer",
							dateOfBirth: "19900115",
							gender: "M",
							status: "Active",
							emailAddress: "john.doe@company.com",
							companyEntryDate: "20220101",
							managerId: "M2001",
							hireDate: "20220101",
							terminationDate: "",
							employmentType: "Permanent",
							isFulltimeEmployee: true,
							employeeClass: "Regular",
							overtimePayed: "Y",
							fte: 1.0,
							department: "IT",
							legalEntity: "LE01",
							phoneNumber: "+1-202-555-0101",
							location: "New York",
							costCenter: "CC1001",
							standardHours: 40,
							jobCode: "ACT001",
							OPERA: "HIR",
						},
						{
							personIdExternal: "E1002",
							firstName: "Emily",
							lastName: "Smith",
							title: "HR Specialist",
							dateOfBirth: "19870322",
							gender: "F",
							status: "Active",
							emailAddress: "emily.smith@company.com",
							companyEntryDate: "20190515",
							managerId: "M2002",
							hireDate: "20190515",
							terminationDate: "",
							employmentType: "Permanent",
							isFulltimeEmployee: true,
							employeeClass: "Professional",
							overtimePayed: "N",
							fte: 1.0,
							department: "Human Resources",
							legalEntity: "LE01",
							phoneNumber: "+1-202-555-0152",
							location: "Chicago",
							costCenter: "CC1002",
							standardHours: 40,
							jobCode: "ACT003",
							OPERA: "MOD",
						},
						{
							personIdExternal: "E1003",
							firstName: "Michael",
							lastName: "Brown",
							title: "Marketing Manager",
							dateOfBirth: "19811205",
							gender: "M",
							status: "Terminated",
							emailAddress: "michael.brown@company.com",
							companyEntryDate: "20150110",
							managerId: "M2003",
							hireDate: "20150110",
							terminationDate: "20230930",
							employmentType: "Permanent",
							isFulltimeEmployee: true,
							employeeClass: "Manager",
							overtimePayed: "N",
							fte: 1.0,
							department: "Marketing",
							legalEntity: "LE02",
							phoneNumber: "+1-202-555-0198",
							location: "Los Angeles",
							costCenter: "CC1003",
							standardHours: 40,
							jobCode: "ACT002",
							OPERA: "TER",
						},
						{
							personIdExternal: "E1004",
							firstName: "Sophia",
							lastName: "Taylor",
							title: "Finance Analyst",
							dateOfBirth: "19950512",
							gender: "F",
							status: "Deleted",
							emailAddress: "sophia.taylor@company.com",
							companyEntryDate: "20200120",
							managerId: "M2004",
							hireDate: "20200120",
							terminationDate: "20210630",
							employmentType: "Contractor",
							isFulltimeEmployee: false,
							employeeClass: "Temporary",
							overtimePayed: "N",
							fte: 0.5,
							department: "Finance",
							legalEntity: "LE01",
							phoneNumber: "+1-202-555-0133",
							location: "Boston",
							costCenter: "CC1004",
							standardHours: 20,
							jobCode: "ACT004",
							OPERA: "DEL",
						},
					],

					orderHeaders: [
						{
							AUFNR: "100001",
							KTEXT: "Produzione A",
							AUART: "ZP01",
							STTXT: "REL",
							WERKS: "1000",
							PLNBEZ: "Material A",
							GAMNG: 500.0,
							GWEMG: 200.0,
							GSTRP: "20250901",
							GLTRP: "20250910",
							OPERA: "INS",
							operations: [
								{
									VORNR: "0010",
									LTXA1: "Operazione 1",
									SSAVD: "20250901",
									SSEVD: "20250905",
									VSTTXT: "ACT",
									ARBPL: "WC01",
									STEUS: "PP01",
									OPERA: "INS",
								},
								{
									VORNR: "0020",
									LTXA1: "Operazione 2",
									SSAVD: "20250906",
									SSEVD: "20250910",
									VSTTXT: "ACT",
									ARBPL: "WC02",
									STEUS: "PP02",
									OPERA: "INS",
								},
							],
						},
						{
							AUFNR: "100002",
							KTEXT: "Produzione B",
							AUART: "ZP02",
							STTXT: "TECO",
							WERKS: "1001",
							PLNBEZ: "Material B",
							GAMNG: 1000.0,
							GWEMG: 1000.0,
							GSTRP: "20250902",
							GLTRP: "20250912",
							OPERA: "MOD",
							operations: [
								{
									VORNR: "0010",
									LTXA1: "Operazione 1",
									SSAVD: "20250902",
									SSEVD: "20250906",
									VSTTXT: "CLO",
									ARBPL: "WC03",
									STEUS: "PP01",
									OPERA: "MOD",
								},
							],
						},
					],
					workCenters: [
						{
							ARBPL: "WC01",
							KTEXT: "Lavorazione A",
							OPERA: "INS",
						},
						{
							ARBPL: "WC02",
							KTEXT: "Lavorazione B",
							OPERA: "INS",
						},
						{
							ARBPL: "WC03",
							KTEXT: "Lavorazione C",
							OPERA: "MOD",
						},
					],
					plants: [
						{
							WERKS: "1000",
							NAME1: "Plant A",
							OPERA: "INS",
						},
						{
							WERKS: "1001",
							NAME1: "Plant B",
							OPERA: "MOD",
						},
					],
					wbeElements: [
						{
							PSPNR: "00000001",
							POSID: "WBS-IT-001",
							POST1: "IT Infrastructure Upgrade",
							PSTRT: "20230101",
							PENDE: "20231231",
							STTXT_EXT: "REL",
							OPERA: "INS",
						},
						{
							PSPNR: "00000002",
							POSID: "WBS-HR-001",
							POST1: "HR Onboarding System",
							PSTRT: "20230401",
							PENDE: "20231031",
							STTXT_EXT: "MOD",
							OPERA: "MOD",
						},
						{
							PSPNR: "00000003",
							POSID: "WBS-MKT-001",
							POST1: "Marketing Campaign 2022",
							PSTRT: "20220115",
							PENDE: "20221015",
							STTXT_EXT: "CLSD",
							OPERA: "DEL",
						},
						{
							PSPNR: "00000004",
							POSID: "WBS-RND-001",
							POST1: "R&D Project Alpha",
							PSTRT: "20230501",
							PENDE: "20241231",
							STTXT_EXT: "REL",
							OPERA: "INS",
						},
						{
							PSPNR: "00000005",
							POSID: "WBS-SUP-001",
							POST1: "Supplier Integration",
							PSTRT: "20230701",
							PENDE: "20231201",
							STTXT_EXT: "REL",
							OPERA: "MOD",
						},
					],
					costCenters: [
						{
							KOSTL: "CC1001",
							BUKRS: "C001",
							LTEXT: "Cost Center for IT Department",
							DATBI: "20230101",
							DATAB: "20241231",
							OPERA: "INS",
						},
						{
							KOSTL: "CC1002",
							BUKRS: "C002",
							LTEXT: "Cost Center for HR Department",
							DATBI: "20230101",
							DATAB: "20241231",
							OPERA: "MOD",
						},
						{
							KOSTL: "CC1003",
							BUKRS: "C003",
							LTEXT: "Obsolete Marketing Cost Center",
							DATBI: "20220101",
							DATAB: "20221231",
							OPERA: "DEL",
						},
					],
					network: [
						{
							AUFNR: "100000000001",
							KTEXT: "Network Description 1",
							PSPNR: "00000001",
							GSTRP: "20230101",
							GLTRP: "20231231",
							OPERA: "INS",
							STATUS: "INS",
							DATEOP: "20231102",
							operations: [
								{
									VORNR: "0001",
									LTXA1: "Operation 1 Description",
									NTANF: "20230110",
									NTEND: "20230120",
									VSTTXT: "REL",
									OPERA: "INS",
									STATUS: "INS",
									DATEOP: "20231102",
								},
								{
									VORNR: "0002",
									LTXA1: "Operation 2 Description",
									NTANF: "20230115",
									NTEND: "20230125",
									VSTTXT: "CLSD",
									OPERA: "MOD",
									STATUS: "MOD",
									DATEOP: "20231102",
								},
							],
							log: [
								{
									AUFNR: "100000000001",
									VORNR: "",
									AUTHMOD: "john.doe",
									MODDATE: "20230901",
									MODTIME: "083015",
									MODOBJ: "KTEXT",
									OLDVAL: "Old Network Description",
									NEWVAL: "Updated Network Description",
									STATUS: "MOD",
								},
								{
									AUFNR: "100000000001",
									VORNR: "0001",
									AUTHMOD: "jane.smith",
									MODDATE: "20230902",
									MODTIME: "101530",
									MODOBJ: "LTXA1",
									OLDVAL: "Initial Description",
									NEWVAL: "Refined Operation 1 Description",
									STATUS: "MOD",
								},
								{
									AUFNR: "100000000001",
									VORNR: "0002",
									AUTHMOD: "admin",
									MODDATE: "20230903",
									MODTIME: "111200",
									MODOBJ: "STATUS",
									OLDVAL: "REL",
									NEWVAL: "CLSD",
									STATUS: "MOD",
								},
								{
									AUFNR: "100000000001",
									VORNR: "0002",
									AUTHMOD: "admin",
									MODDATE: "20230703",
									MODTIME: "111200",
									MODOBJ: "",
									OLDVAL: "",
									NEWVAL: "",
									STATUS: "INS",
								},
							],
						},
						{
							AUFNR: "100000000002",
							KTEXT: "Network Description 2",
							PSPNR: "00000002",
							GSTRP: "20230201",
							GLTRP: "20231231",
							OPERA: "MOD",
							STATUS: "MOD",
							DATEOP: "20231102",
							operations: [
								{
									VORNR: "0001",
									LTXA1: "Operation 1 Description",
									NTANF: "20230205",
									NTEND: "20230215",
									VSTTXT: "REL",
									OPERA: "MOD",
									STATUS: "MOD",
									DATEOP: "20231102",
								},
							],
						},
						{
							AUFNR: "100000000003",
							KTEXT: "Network Description 1",
							PSPNR: "00000003",
							GSTRP: "20230101",
							GLTRP: "20231231",
							OPERA: "INS",
							STATUS: "INS",
							DATEOP: "20231102",
							operations: [
								{
									VORNR: "0001",
									LTXA1: "Operation 1 Description",
									NTANF: "20230110",
									NTEND: "20230120",
									VSTTXT: "REL",
									OPERA: "INS",
									STATUS: "INS",
									DATEOP: "20231102",
								},
								{
									VORNR: "0002",
									LTXA1: "Operation 2 Description",
									NTANF: "20230115",
									NTEND: "20230125",
									VSTTXT: "CLSD",
									OPERA: "MOD",
									STATUS: "MOD",
									DATEOP: "20231102",
								},
							],
							log: [
								{
									AUFNR: "100000000003",
									VORNR: "",
									AUTHMOD: "john.doe",
									MODDATE: "20230901",
									MODTIME: "083015",
									MODOBJ: "KTEXT",
									OLDVAL: "Old Network Description",
									NEWVAL: "Updated Network Description",
									STATUS: "MOD",
								},
								{
									AUFNR: "100000000003",
									VORNR: "0001",
									AUTHMOD: "jane.smith",
									MODDATE: "20230902",
									MODTIME: "101530",
									MODOBJ: "LTXA1",
									OLDVAL: "Initial Description",
									NEWVAL: "Refined Operation 1 Description",
									STATUS: "MOD",
								},
								{
									AUFNR: "100000000003",
									VORNR: "0002",
									AUTHMOD: "admin",
									MODDATE: "20230903",
									MODTIME: "111200",
									MODOBJ: "STATUS",
									OLDVAL: "REL",
									NEWVAL: "CLSD",
									STATUS: "MOD",
								},
								{
									AUFNR: "100000000003",
									VORNR: "0002",
									AUTHMOD: "admin",
									MODDATE: "20230703",
									MODTIME: "111200",
									MODOBJ: "",
									OLDVAL: "",
									NEWVAL: "",
									STATUS: "INS",
								},
							],
						},
					],
				});
			},
		};
	}
);
